name: Build Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Pack BepInEx plugin
        run: |
          mkdir package
          mkdir package\BepInEx
          mkdir package\BepInEx\plugins
          mkdir package\BepInEx\plugins\GreyAnnouncer

          copy publish\GreyAnnouncer.dll package\
          copy publish\FFmpeg.AutoGen.dll package\
          copy publish\Newtonsoft.Json.dll package\

      - name: Create zip
        run: powershell Compress-Archive package GreyAnnouncer.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GreyAnnouncer
          path: GreyAnnouncer.zip
